# docs at: https://eslint.org/docs/latest/use/configure/
env:
  browser: true
  es2021: true
  "react-native/react-native": true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-native/all
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  emcaFeatures:
    - jsx: true
plugins:
  - react
  - react-native
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
